/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'takahara' at '17/12/13 15:41' with Gradle 2.14.1
 *
 * @author takahara, @date 17/12/13 15:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
